name: Pumpkin-Android-AutoBuild

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */12 * * *'

jobs:
  check-and-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Tracker
        uses: actions/checkout@v4

      - name: Check for Updates
        id: check_version
        run: |
          LATEST_ID=$(git ls-remote https://github.com/Pumpkin-MC/Pumpkin.git HEAD | awk '{print $1}')
          echo "latest_id=$LATEST_ID" >> $GITHUB_ENV
          
          if [ -f version_tracker.txt ]; then
            OLD_ID=$(cat version_tracker.txt)
          else
            OLD_ID="none"
          fi
          
          if [ "$LATEST_ID" = "$OLD_ID" ]; then
            echo "match=true" >> $GITHUB_OUTPUT
            echo "No new updates. Skipping build."
          else
            echo "match=false" >> $GITHUB_OUTPUT
            echo "New version found! Starting build..."
          fi

      - name: Download Pumpkin Source
        if: steps.check_version.outputs.match == 'false'
        uses: actions/checkout@v4
        with:
          repository: 'Pumpkin-MC/Pumpkin'
          path: 'pumpkin-source'

      - name: Patch 32-bit Bug in PumpkinMC
        if: steps.check_version.outputs.match == 'false'
        working-directory: ./pumpkin-source
        run: |
          sed -i 's/i64::from_ne_bytes(height_bit_bytes)/isize::from_ne_bytes(height_bit_bytes) as i64/g' pumpkin-world/src/chunk/mod.rs

      - name: Setup Rust
        if: steps.check_version.outputs.match == 'false'
        uses: dtolnay/rust-toolchain@stable

      - name: Install Cross
        if: steps.check_version.outputs.match == 'false'
        run: cargo install cross --locked

      - name: Build for Android 32-bit
        if: steps.check_version.outputs.match == 'false'
        working-directory: ./pumpkin-source
        env:
          CARGO_PROFILE_RELEASE_PANIC: abort
          # THE FIX: This forces the modern compiler to bundle the missing Android 6 system libraries!
          RUSTFLAGS: "-C link-arg=-Wl,-Bstatic -C link-arg=-lunwind -C link-arg=-Wl,-Bdynamic"
        run: cross build --target armv7-linux-androideabi --release

      - name: Upload Finished Server
        if: steps.check_version.outputs.match == 'false'
        uses: actions/upload-artifact@v6
        with:
          name: pumpkin-android-32bit
          path: pumpkin-source/target/armv7-linux-androideabi/release/pumpkin

      - name: Save Version ID
        if: steps.check_version.outputs.match == 'false'
        run: |
          echo "${{ env.latest_id }}" > version_tracker.txt
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version_tracker.txt
          git commit -m "Updated tracker to version ${{ env.latest_id }}"
          git push
